# Load required libraries
source(here::here("main.R"));

# Load functions
source(here::here("CEPI_DiseaseX_Modelling/R/functions_multivaccine.R"))

# https://github.com/mrc-ide/squire.page/blob/main/R/booster_model.R#L841 - ref for run_booster function
# https://github.com/mrc-ide/squire.page/blob/main/R/booster_model.R#L286 - ref for parameters_booster function

## Notes of things to do:
#### make sure Azra's IFR rescaling calc still works even though she's using a contact matrix for each of these countries
#### squire.page:::probs_booster$rel_infectiousness_vaccinated is making some pretty big assumptions about impact on transmission (I think)

# Defining Parameters for Model Runs

### Demographic Parameters
target_pop <- 1e6                                                        # size of the population to simulate 
income_group <- "UMIC"                                                    # income strata 
rep_country <- get_representative_country(income_group = income_group)   # representative country  
raw_pop <- squire::get_population(country = rep_country)$n                   
standard_pop <- round(raw_pop * target_pop / sum(raw_pop))               # standardised population size
mm <- squire::get_mixing_matrix(country = rep_country)                   # mixing matrix for that country

### Healthcare Parameters
hosp_bed_capacity <- target_pop * 100                                           # hospital bed capacity
ICU_bed_capacity <- target_pop * 100                                            # ICU bed capacity

### Disease Severity Parameters (NEED TO CHECK THESE AND TALK TO AZRA ABOUT THEM)
ifr_scaling <- 0.1                                                      # Azra's IFR scaling thing (need to check, especially given generated by hand in spreadsheet and country-specific contact matrices being used)
prob_severe_death_treatment <- get_ifr_dist()                            # probability of death given severe disease and treatment
prop_hosp_severe <- case_when(ifr_scaling == 1 ~ 0.5, 
                              ifr_scaling == 0.5 ~ 0.1,
                              ifr_scaling == 0.1 ~ 0.1,
                              ifr_scaling == 2 ~ 0.8)
ratio_deaths_severe_to_hosp <- case_when(ifr_scaling == 1 ~ 0.29,
                                         ifr_scaling == 0.5 ~ 0.29,
                                         ifr_scaling == 0.1 ~ 0.06,
                                         ifr_scaling == 2 ~ 0.39)
ratio_deaths_non_severe_to_deaths_severe <- case_when(ifr_scaling == 1 ~ 0.4,
                                                      ifr_scaling == 0.5 ~ 0.215,
                                                      ifr_scaling == 0.1 ~ 0.215,
                                                      ifr_scaling == 2 ~ 0.6)
prob_hosp <- ratio_deaths_severe_to_hosp * prob_severe_death_treatment
prob_severe <- prop_hosp_severe * prob_hosp
prob_non_severe_death_treatment <- ratio_deaths_non_severe_to_deaths_severe * prob_severe_death_treatment

### Epidemiological Parameters 
R0 <- 2.5                # R0
seeding_cases <- 10      # define as the number of cases at first sequencing - will need to explore

### Vaccination Parameters
efficacy_infection_v1 <- 0.35              # vaccine efficacy against infection - BNPC
efficacy_disease_v1 <-  0.8                # vaccine efficacy against disease - BNPC
efficacy_infection_v2 <- 0.55              # vaccine efficacy against infection - specific vaccine
efficacy_disease_v2 <-  0.9                # vaccine efficacy against disease - specific vaccine
duration_R <- 10000 * 365                  # duration of infection-induced immunity - assumed large as not considering waning (currently)
duration_V <- 10000 * 365                  # duration of vaccine-induced immunity for both vaccines - assumed large as not considering waning (currently) - also need to make vaccine specific
dur_vacc_delay <- 5                       # mean duration from vaccination to protection
                                           # changing this alters the point the boostered elderly coverage tops out - AGAIN NOTE THIS IS CONCERNING, WONDER WHETHER SECONDARY DOSES IS FALLING OUTSIDE OF THE PRIMARY DOSES TT AND HENCE NOT BEING DONE. 
vaccine_1_start <- 80 #50 #5               # time when BNPC starts being distributed
vaccine_2_start <- 5000#250 #250 #10            # note that this needs to be after v1 has been completed - WHY - NEED TO CHECK THIS???
coverage <- 0.75                           # proportion of the population vaccinated
vaccination_rate <- 0.02                   # vaccination rate per week as percentage of population
                                           # From Azra/SAFIR: 5% per week in HIC/UMIC, 2% per week in LMIC/LIC
                                           #                  = 16 weeks (112 days) for HIC/UMIC, 40 weeks (280 days) for LMIC/LIC to reach 80% coverage
lower_priority <- 13                       # index of the youngest age group given priority w.r.t vaccines (14 = 60+)
lower_vaccine <- 4                         # index of the youngest age group that *receives* vaccines (4 = 15+)
priority_age_groups <- lower_priority:17   # creating the index list for priority age groups  
vaccination_age_groups <- lower_vaccine:17 # creating the index list for vaccinable age-groups
vaccine_coverage_mat <-                    # matrix (col = age group, row = prioritisation step) of how to assign vaccines to different age-groups according to priority
  matrix(c(rep(0, 17 - length(priority_age_groups)), rep(coverage, length(priority_age_groups)), 
           rep(0, 17 - length(vaccination_age_groups)), rep(coverage, length(vaccination_age_groups))), ncol = 17, byrow = TRUE)
second_dose_delay <- 5                     # controls how many days after "1st dose" people receive second dose; see here: https://github.com/mrc-ide/squire.page/blob/main/inst/odin/nimue_booster.R#L427-L430
                                           # we're ignoring first doses, so skipping people straight to being "fully vaccinated" with the vaccine we're interested in
v1_daily_doses <- vaccination_rate * sum(standard_pop) / 7  # what about the coverage stuff (i.e. does not assume coverage = 1, rather than e.g. 0.8)
v2_daily_doses <- vaccination_rate * sum(standard_pop) / 7  # what about the coverage stuff (i.e. does not assume coverage = 1, rather than e.g. 0.8)

## 60+s receive primary (BNPCV) and booster (diseaseX-specific); under 60s receive just primary (diseaseX-specific)
elderly_pop_to_vaccinate <- sum(standard_pop[priority_age_groups]) * coverage
time_to_coverage_v1 <- ceiling(elderly_pop_to_vaccinate / v1_daily_doses) # calculated so that we only vaccinate 60+s with the stockpiled BNPSC
                                                                          # This is required as we're using a single vaccine_efficacy_infection
                                                                          # matrix and so we have to stop vaccinating when we've covered 60+s
                                                                          # as otherwise according to the matrix, they'd start receiving diseaseX-specific

# Note that the below assumes 1) only 60+ vaccinated with BNPSC vaccine
# 2) no synergy between BNPSC and diseaseX-specific vaccine

# primary doses are disease X specific for younger folks and BNPCV for older folks
time_to_coverage_v2_elderly <- ceiling(elderly_pop_to_vaccinate/v2_daily_doses)
primary_doses <- c(0, v1_daily_doses, 0, v2_daily_doses) # final quantity here is doses after final quantity in tt_primary_doses
tt_primary_doses <- c(0, vaccine_1_start, round(vaccine_1_start + time_to_coverage_v1), vaccine_2_start + time_to_coverage_v2_elderly) # consider what it means when this stops too soon 
### -> Between time [0] and [vaccine_1_start] is when no one is being vaccinated
### -> Between [vaccine_1_start] and [round(vaccine_1_start + time_to_coverage_v1] is when  60+s start getting vaxxed with BNPSC, 
### -> Between [round(vaccine_1_start + time_to_coverage_v1] and [vaccine_2_start + time_to_coverage_v2_elderly], no one is being vaxxed
###    with primary doses. This is because either diseaseX vaccinate hasn't been developed yet, or is still being used to vaccinate
###    elderly. 
### -> After [vaccine_2_start + time_to_coverage_v2_elderly], all elderly have been vaccinated with diseaseX specific (in booster) and 
###    so we can begin vaccinating younger folks with the diseaseX specific vaccine (which is their "primary" vaccine, in contrast to
##     the elderly, for whom "primary" vaccine is BNPSC). Because we've hit the coverage targets in the elderly, the young are prioritised instead.

booster_doses <- c(0, v2_daily_doses, 0) 
tt_booster_doses <- c(0, vaccine_2_start, vaccine_2_start + time_to_coverage_v2_elderly) # note that if this stops too soon, you'll end up with elderly age-groups not being fully boosted - WHY IS THIS???
### -> Between time [0] and [vaccine_2_start], diseaseX specific vaccine hasn't been developed and so isn't used.
### -> Between time [vaccine_2_start] and [vaccine_2_start + time_to_coverage_v2_elderly], diseaseX specific is used
###    to vaccinate elderly - for them, that's as a booster.
### -> After [vaccine_2_start + time_to_coverage_v2_elderly], elderly are vaccinated and only need to diseaseX specific vaccine
###    the younger folks. For them, diseaseX specific vaccine is their primary series, and so that's handled
###    by the primary-doses related code above. 
### -> vaccine_2_start + time_to_coverage_v2_elderly is when we want to stop boosting anybody

#setup as a matrix giving VE per age group
ve_v1 <- list(infection = efficacy_infection_v1, disease = efficacy_disease_v1)
ve_v2 <- list(infection = efficacy_infection_v2, disease = efficacy_disease_v2)
ve_i_booster_elderly <- c(ve_v1$infection, ve_v1$infection, ve_v1$infection, 0, ve_v2$infection, ve_v2$infection, 0) 
ve_i_booster_non_elderly <- c(ve_v2$infection, ve_v2$infection, ve_v2$infection, 0, ve_v2$infection, ve_v2$infection, 0)
vaccine_efficacy_infection <- matrix(c( rep(ve_i_booster_non_elderly, 17 - length(priority_age_groups)), 
                                        rep(ve_i_booster_elderly, length(priority_age_groups)) ), ncol = 17)
# each col is for an age-group, the diff vaccine efficacies after different doses
# 1 is primary series dose; 2 is second dose 1st comp; 3 is second dose 2nd comp; 4 is waned; 5 is booster first comp; 6 is booster second comp; 7 is waned.

#repeat for disease 
ve_i_booster_elderly <- c(ve_v1$disease, ve_v1$disease, ve_v1$disease, 0, ve_v2$disease, ve_v2$disease, 0) 
ve_i_booster_non_elderly <- c(ve_v2$disease, ve_v2$disease, ve_v2$disease, 0, ve_v2$disease, ve_v2$disease, 0)
vaccine_efficacy_disease <- matrix(c( rep(ve_i_booster_non_elderly, 17 - length(priority_age_groups)), 
                                      rep(ve_i_booster_elderly, length(priority_age_groups)) ), ncol = 17)

vaccine_booster_follow_up_coverage <- c(rep(0, min(priority_age_groups) - 1), rep(1, length(priority_age_groups)))
vaccine_booster_initial_coverage <- c(rep(0, min(priority_age_groups) - 1), rep(1, length(priority_age_groups)))

# Running the model
orig_tt_primary_doses <- tt_primary_doses
tt_primary_doses <- c(0, 80, 122, 4000)
runtime <- 1000
tic()
r1 <- run_booster( 
  time_period = runtime,                                                     # time to run the model for
  population = standard_pop,                                                 # population to be simulated
  contact_matrix_set = mm,                                                   # mixing matrix
  R0 = R0,                                                                   # basic reproduction number
  tt_R0 = 0,                                                                 # timing of changes in R0 to mimic NPIs
  hosp_bed_capacity = hosp_bed_capacity,                                     # hospital bed capacity
  ICU_bed_capacity = ICU_bed_capacity,                                       # ICU bed capacity
  prob_hosp = prob_hosp * 0,                                                     # probability of requiring hospitalisation
  prob_severe = prob_severe * 0,                                                 # probability of requiring ICU stay
  prob_non_severe_death_no_treatment = prob_non_severe_death_treatment * 0 ,      # prob death given non-severe disease
  prob_severe_death_treatment = prob_severe_death_treatment,                 # prob death given severe disease
  dur_R = duration_R,                                                        # duration of immunity following infection
  seeding_cases = seeding_cases,                                             # number of cases outbreak starts with
  vaccine_coverage_mat = vaccine_coverage_mat,                               # matrix (col = age group, row = prioritisation step) of how to assign vaccines to different age-groups according to priority
  vaccine_efficacy_infection = vaccine_efficacy_infection,                   # vaccine efficacy against infection (matrix where row = age group, column = vaccine/dose)
  vaccine_efficacy_disease = vaccine_efficacy_disease,                       # vaccine efficacy against disease (matrix where row = age group, column = vaccine/dose)
                                                                             # --> columns = (first dose, second dose, second dose, waned, booster, booster, waned) 
                                                                             # --> note in this hacky version, for age > priority group, first vaccine = BNPSC, second = diseaseX; for age < priority group, only have first vaccine which is diseaseX 
  second_dose_delay = second_dose_delay,                                     # delay between receipt of first and second dose (ignored here as we're modelling single dose vaccines) - second doses are assigned
                                                                             # automatically in squire.page, at second_dose_delay days after the primary dose was delivered
  dur_V = rep(duration_V/2, 4),                                              # duration of vaccination-derived immunity (currently not vaccine specific) 
                                                                             # --> first two elements are for primary vaccine, elements 3 and 4 are for booster, half duration in each compartment giving erlang-2 waning
                                                                             # --> gets converted into gamma_vaccine by https://github.com/mrc-ide/squire.page/blob/073ec7d107419d95aabfaba3735ffdc2609195a4/R/booster_model.R#L575-L584
  protection_delay_rate = 1/dur_vacc_delay,                                  # Delay between full initial vaccine course and protection (see run_booster -> parameters_booster -> apply_dose_delay_booster in squire.page)
                                                                             # Combines with "second_dose_delay" above to generate the amount of time between first dose receipt and second dose receipt (under assumption)
                                                                             # that individuals are protected immediately after receiving second dose. I.e. way of aggregating both delay between doses and delay between dose and protection. 
  primary_doses = primary_doses,                                             # Primary dose (i.e. first dose, with second dose then implicitly generated under the hood) vaccination rate 
  tt_primary_doses = tt_primary_doses,                                       # Timings for variable primary dose vaccination rate 
  booster_doses = booster_doses,                                             # Booster dose vaccination rate 
  tt_booster_doses = tt_booster_doses,                                       # Timings for variable booster dose vaccination rate 
  vaccine_booster_follow_up_coverage = vaccine_booster_follow_up_coverage,   # Vector describing which age-groups are eligible for follow-up boosters (re-boostering, basically)
  vaccine_booster_initial_coverage = vaccine_booster_initial_coverage)       # Vector describing which age-groups are eligible for initial boosters
toc()

# first vaccine = BNPSC vaccine for priority age-groups, disease X specific for rest
# booster vaccine = disease X specific for priority age-groups
check <- nimue::format(r1, compartments = c("vaccinated_first_dose", "vaccinated_second_dose", "vaccinated_booster_dose"), 
                       reduce_age = FALSE) %>%
  filter(t > 1,
         compartment == "vaccinated_first_dose" | compartment == "vaccinated_second_dose" | compartment == "vaccinated_booster_dose") %>%
  group_by(replicate, t, age_group) 
pop_df <- data.frame(age_group = sort(unique(check$age_group)), population = standard_pop)
check <- check %>%
  left_join(pop_df, by = "age_group") %>%
  mutate(prop = value / population) 
# ggplot() +
#   geom_line(data = check, aes(x = t, y = prop, col = compartment)) +
#   facet_wrap(~age_group) +
#   lims(y = c(0, 1), x = c(0, 1000)) 
ggplot() +
  geom_line(data = check[check$age_group == "60-65", ], aes(x = t, y = prop, col = compartment)) +
  facet_wrap(~age_group) +
  geom_vline(aes(xintercept = tt_primary_doses)) +
  scale_x_continuous(breaks = c(0, 20, 40, 60, 80, 100, 200, 400, 600),
                     limits = c(0, 600)) +
  lims(y = c(0, 1)) 

       